### ISSUE TITLE
Consider dictionary semantics more carefully.

### ISSUE THREAD

**Issue by jameshaydon** [oscoin/radicle#112]
Radicle is meant to be a fully specified language, but the semantics of dictionaries are rather bizarre.

The default ordering of values is relevant in the evaluation of a dict (when resolving key-collisions), or just when calling `seq`, and _all_ values are permitted as keys in dicts. Thus for example:

```scheme
(define a (ref 0))
(define b (ref 0))
...
(define d {a 0 b 1})
(seq d)
```

The resulting list is ordered according to the _addresses_ in the refs, but the (order of the) addresses of refs should not enter in the semantics of the language. Things are even more bizarre when using functions as keys!

**Proposal:** Creating a dict with non-[hashable](https://github.com/oscoin/radicle/issues/106#issuecomment-424114048) keys results in an error.

**Comment by luqui** [comment]
Another possibility is to remove the relevance of the ordering somehow.  E.g. requiring a comparison function for sorting whenever iterating over keys.  This solution might be a bit ... radicle .......... but something to consider.

**Comment by jameshaydon** [comment]
> requiring a comparison function for sorting whenever iterating over keys

Unfortunately, I think the ordering of the keys is relevant at a more fundamental level. Dicts are evaluated, and when that happens:
- The order of evaluation is according to the order of the keys,
- Two distinct keys may now evaluate to equal values, and now which associated value to choose is dependent on the order of the old keys.

Here is an example:

```
rad> (def x (ref 0))
()
rad> (def y (ref 0))
()
rad> (def const (fn [x y] x))
()
rad> (def d {(const 0 x) 1 (const 0 y) 2})
()
rad> d
{0.0 2.0}
```

**Comment by luqui** [comment]
I don't really follow this example.  Does this not essentially reduce to:

    (def d {0 1 0 2})
    -->
    (def d {0 2})

*after which* the dictionary value is made?  That is, the evaluation order is a property of the dictionary *constructor*, and the ordering of keys doesn't matter once we have an actual dictionary.

**Comment by jameshaydon** [comment]
```
rad> (def x (ref 0))
()
rad> (def y (ref 0))
()
rad> (def const (fn [a b] a))
()
rad> {(const 0 x) 1 (const 0 y) 2}
{0.0 2.0}
rad> {(const 0 y) 1 (const 0 x) 2}
{0.0 1.0}
```

**Comment by luqui** [comment]
Whattt??? That's ludicrous!
