### ISSUE TITLE
Validation library

### ISSUE THREAD

**Issue by geigerzaehler** [oscoin/radicle#149]
For safety and security it will be essential to validate data that is stored on chain. Radicle should provide a library that does this kind of validation in an extensible and composable way.

Clojure’s [spec](https://clojure.org/guides/spec) library seems to be a good template for this.

**Comment by jameshaydon** [comment]
I totally agree but I am wondering about the possibility of radicle having types soon which would either make something like `spec` not needed or at least implemented in a very different way. I suggest we implement some very minimal spec-like features for the moment, until we have a stab at types? @jkarni

**Comment by luqui** [comment]
Oh are types on the horizon; I wasn't aware of that?  Are there any existing design documents or discussions regarding this?  (Cursory search reveals nothing)

**Comment by jameshaydon** [comment]
Minimally done in #188.
