### ISSUE TITLE
In-language documentation

### ISSUE THREAD

**Issue by jkarni** [oscoin/radicle#15]
- There should be a `doc` function which, given an identifier, returns the documentation for that identifier (if it exists). 
- There should be a way of documenting new functions that integrates with that `doc` function.
- Existing primops should be documented.

I initially imagined there was good reason to have `doc` work only in the impure environment (since we want to maintain referential transparency). But I now realize `doc` can work on *quoted* identifiers and maintain referential transparency. (Note that `quote` is not a function, and in typed settings at least for subtle and profound reasons that I only half-remember, so there's no function from an *unquoted* value to it's documentation.)

**Comment by jameshaydon** [comment]
Fixed in #177.
