### ISSUE TITLE
Identifiers with numeric prefix nor parsed

### ISSUE THREAD

**Issue by jkarni** [oscoin/radicle#16]
E.g. `-93G`.

**Comment by luqui** [comment]
I'm taking this because I simply cannot abide test flakiness

**Comment by luqui** [comment]
I think the correct behavior here is for `-93G` to indeed be a parse error, rather than an identifier, so the bug is just in generating identifiers.  Consider a typo like `3O`, or the common notation from C `42.0f`.  I don't think we want these to be interpreted as identifier atoms.
