### ISSUE TITLE
Write REPL history to file

### ISSUE THREAD

**Issue by geigerzaehler** [oscoin/radicle#172]
The REPL input history is never written to the configure history file by `haskeline`.

The reason is that `haskeline` only writes the file if the `InputT` monad exits properly, that is without throwing an exceptions. At the moment the `radicle` binaries only exit on Ctrl-C and EOF. Both cases throw an exception.

**Comment by kim** [comment]
https://github.com/judah/haskeline/pull/36
https://github.com/judah/haskeline/issues/5

**Comment by jkarni** [comment]
I don't think that's the problem. The issue is that the executable doesn't write to the file if the file/dir don't exist.

**Comment by geigerzaehler** [comment]
Indeed it works if I do `mkdir ~/.local/share/rad`. Can we change the `getHistory` function to ensure that the directory exists?

**Comment by jkarni** [comment]
:+1:
