### ISSUE TITLE
Don't use `do` when sending files

### ISSUE THREAD

**Issue by jkarni** [oscoin/radicle#202]
Currently when sending an entire file with `send-code!` or `send-prelude!`, we wrap the code in a `do` block. This has a couple of problems:

1) If there is an eval redef within the `do` block, it will affect the sent code differently than the local one, since eval redefs take effect at the new toplevel
2) If there is an eval redef that removes `do` support, these functions won't work at all, even if trying to send a valid file

Probably the best thing to do is change the `submit` endpoint (and `send!`) so they can take any number of expressions instead of just one. Then we can just submit an entire file as is.

One subtlety is that currently `send!` takes an actual `Value`, not a string/text. This means we first parse as value, then again pretty print on the way out. So the sent code may look textually different than the source file, including different error locations. We talked about having a canonical form on chains, so maybe this isn't a bad thing (except for the extra processing), but it's good to be aware of.

**Comment by jameshaydon** [comment]
> Probably the best thing to do is change the submit endpoint (and send!) so they can take any number of expressions instead of just one. Then we can just submit an entire file as is.

What is the semantics of this endpoint? Are all or none of the transactions executed atomically?

> So the sent code may look textually different than the source file, including different error locations.

Also missing comments.

**Comment by jkarni** [comment]
> What is the semantics of this endpoint? Are all or none of the transactions executed atomically?

No. I agree that's a problem. `do` can in some cases recover that atomicity, but not in general (e.g., the `issues` chain already doesn't allow that). I don't really know whether making `do` survive eval-redefs is the best way to do this, or if that'd involve some other check. Consider that:

- a) Sometimes we want atomicity. I.e., all transactions must make it, in the order specified, without new transactions interleaved, or else none at all
- b) Sometimes we just want all transactions to make it, whether or not there are interleavings
- c) Sometimes we don't care at all whether other transactions made it.

There seem to be ways not involving `do` of getting a) and b), such as checking the last uuid, or the used uuids. Dunno if that's better or worse.

I'm going to close this issues, as it was done in #198. Happy to open another one in which to discuss atomicity.
