### ISSUE TITLE
Switch to gpg-me?

### ISSUE THREAD

**Issue by jkarni** [oscoin/radicle#222]
As discussed on IRC, some advantages of doing so:

1) An existing system for associating keys with identities (including crypto parties)
2) Web of trust
3) A nice passphrase system, so it's obvious when expressions require signatures
4) A canonical short form

The downside is the extra dependency.

**Comment by kim** [comment]
I am skeptical of imposing a PKI, especially for the main chain (which the short form would imply).

**Comment by jkarni** [comment]
Sorry, to be clear, by "canonical short form" I meant the fingerprint/key id (or short key id) as in [RFC 4880](https://tools.ietf.org/html/rfc4880#section-12.2). With that clarification, I don't think we're imposing a PKI? We can avail ourselves of identities recognized/trusted by the user in making "pet names" for keys, but those aren't shared (beyond the usual web-of-trust sharing) and aren't part of anything in remote chains.

**Comment by kim** [comment]
Maybe I'm not understanding what you want to use this for - if you just want to save yourself serialising the public key repeatedly, then the receiver / verifier has to pull the key by fingerprint from some PKI. This isn't very practical for the consensus side of things.

We also kind of adopted the "multihash" encoding from the PL folks, perhaps they also have a "multipubkey" thing?

As mentioned elsewhere, I'm also not sure if we want to standardise on RSA keys, or else support a range of key algorithms.

**Comment by cloudhead** [comment]
I'm not sure what this entails for the p2p layer. Does gpg-me support ECDSA? Where would this be used?

**Comment by cloudhead** [comment]
What's the issue with using a similar scheme as the other p2p and blockchain protocols? SSB is the simplest: https://ssbc.github.io/scuttlebutt-protocol-guide/#keys-and-identities - just a base64 of the key. Ethereum and bitcoin are similar, they hash the key and take the lower 160 bits.

We could use the same system as in oscoin: multihash + base58 instead.

**Comment by jkarni** [comment]
Alright, evidently not a very popular idea. Closing.

**Comment by kim** [comment]
I’m not sure we should completely dismiss this - consider the scenario where people have set up their git to sign commits (which seems to become increasingly popular). Now, it’s perhaps not the most brilliant idea to use the same key for radicle as well (because RSA), but being able to add an (ECSDA) identity to my keyring and have the CLI/REPL be able to use this does seem like a nice feature. Ie. use gpg as a keystore
