### ISSUE TITLE
Should send! resolve vars?

### ISSUE THREAD

**Issue by jkarni** [oscoin/radicle#70]
We wrote some eval functions for different chains. Currently, if we `(send! "chain" 'my-custom-eval)`, that only works if the other chain knows what `my-custom-eval` is (and what the variables it uses are). This makes it an annoyance to send things, since you can't really abstract over the process. 

If we resolved everything down to primops (plus maybe prelude), this wouldn't be a problem.

**Comment by luqui** [comment]
Isn't there another issue, in that the purpose of a custom eval is to restrict what future operations are possible on a chain.  If we can send closures, wouldn't it be possible to circumvent whatever special logic the custom eval was trying to impose?

**Comment by jkarni** [comment]
> If we can send closures, wouldn't it be possible to circumvent whatever special logic the custom eval was trying to impose?

The proposal isn't to change what remote chains accept, just what gets sent. E.g.:

```
(def x 3)
(def y (fn [] x))
(send! chain (resolve-vars y))
;; equivalent to
(send! chain '(fn [] 3))
```

But I agree this would likely result in unreasonable messes. Not sure if there's a version of this idea that's worth trying to salvage, so will close.
