### ISSUE TITLE
Split server into CentralChain, and ChainApi

### ISSUE THREAD

**Issue by jameshaydon** [oscoin/radicle#81]
- `CentralChain` is a centralised radicle chain (what we have now, but will be replaced by a decentralised version)
- `ChainApi` is a server that connects to a chain and provides a nice API to interact with it, including viewing input, viewing outputs, submitting expressions, etc.

**Comment by jameshaydon** [comment]
@jkarni @geigerzaehler Done? No longer relevant?

**Comment by geigerzaehler** [comment]
I think this is no longer relevant.
